-- Permanent case deletion (Papirkurv) needs purchases to survive their
-- case being deleted, for accounting/receipt history. Today's FK is
-- "on delete cascade", which would silently destroy purchase records
-- along with the case. This makes case_id nullable and switches the FK
-- to "on delete set null" instead -- the purchase row (amount, product,
-- Stripe ids, status, dates) is self-contained and stays intact, only
-- the case link goes null. The old FK's name is looked up dynamically
-- instead of hardcoded, since it was auto-generated by Postgres and this
-- avoids any risk of guessing it wrong against the live database.
do $$
declare
  fk_name text;
begin
  select conname into fk_name
  from pg_constraint
  where conrelid = 'public.purchases'::regclass
    and confrelid = 'public.cases'::regclass
    and contype = 'f';

  if fk_name is not null then
    execute format('alter table public.purchases drop constraint %I', fk_name);
  end if;
end $$;

alter table public.purchases alter column case_id drop not null;

alter table public.purchases
  add constraint purchases_case_id_fkey
  foreign key (case_id) references public.cases (id) on delete set null;
